// MySQL 8.0.17+ / MariaDB 10.6+, InnoDB. No extensions, triggers or server-wide privileges.
const id = 'id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY';
const time = (name: string, required = false) =>
  `${name} DATETIME(3)${required ? ' NOT NULL DEFAULT CURRENT_TIMESTAMP(3)' : ''}`;
const created = time('created_at', true),
  updated = time('updated_at', true);
const json = (name: string, fallback?: string) =>
  `${name} JSON${fallback === undefined ? '' : ` NOT NULL DEFAULT ('${fallback}')`}`;
const ref = (name: string, table: string, required = false, cascade = false) =>
  `${name} CHAR(36) CHARACTER SET ascii COLLATE ascii_bin${required ? ' NOT NULL' : ''}, FOREIGN KEY (${name}) REFERENCES ${table}(id)${cascade ? ' ON DELETE CASCADE' : ''}`;
const table = (name: string, fields: string[]) =>
  `CREATE TABLE IF NOT EXISTS ${name} (${fields.join(',\n')}) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`;

// Checked through information_schema so upgrades work on both MySQL and MariaDB.
export const mysqlAddColumns = [
  ['agents', 'public_display_name', 'VARCHAR(80)'],
  ['users', 'line_display_name', 'VARCHAR(255)'],
  ['users', 'line_profile_checked_at', 'DATETIME(3)'],
  ['agents', 'line_identity_source', 'VARCHAR(20)'],
  ['agents', 'line_login_channel_id', 'VARCHAR(100)'],
  ['staff_sso_transactions', 'line_user_id', 'VARCHAR(191)'],
  ['staff_sso_transactions', 'line_login_channel_id', 'VARCHAR(100)'],
  ['staff_sso_transactions', 'return_path', 'VARCHAR(250)'],
] as const;

export const mysqlSchema = [
  table('schema_migrations', ['version INT PRIMARY KEY', time('applied_at', true)]),
  table('agents', [
    id,
    'name VARCHAR(255) NOT NULL',
    'email VARCHAR(320) NOT NULL UNIQUE',
    'password_hash TEXT NOT NULL',
    "role VARCHAR(20) NOT NULL CHECK(role IN ('ADMIN','AGENT','REVIEWER'))",
    'active BOOLEAN NOT NULL DEFAULT true',
    created,
    'line_user_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin UNIQUE',
    'line_alerts_enabled BOOLEAN NOT NULL DEFAULT false',
  ]),
  table('auth_sessions', [
    'token_hash VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    ref('agent_id', 'agents', true, true),
    'expires_at DATETIME(3) NOT NULL',
    created,
  ]),
  table('users', [
    id,
    'line_user_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE',
    'cusa_sub VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin UNIQUE',
    'email VARCHAR(320)',
    'name VARCHAR(255) NOT NULL',
    'department VARCHAR(255)',
    json('roles', '[]'),
    "avatar_color VARCHAR(30) NOT NULL DEFAULT 'sage'",
    'blocked BOOLEAN NOT NULL DEFAULT false',
    'rich_menu_id VARCHAR(191)',
    time('linked_at'),
    created,
    updated,
    json('interest_tags', '[]'),
    'rich_menu_target VARCHAR(191)',
    'rich_menu_revision INT NOT NULL DEFAULT 0',
    "rich_menu_status VARCHAR(30) NOT NULL DEFAULT 'UNCHANGED'",
  ]),
  table('teams', [
    id,
    'name VARCHAR(200) NOT NULL UNIQUE',
    "description TEXT NOT NULL DEFAULT ('')",
    'active BOOLEAN NOT NULL DEFAULT true',
    created,
  ]),
  table('team_members', [
    ref('team_id', 'teams', true),
    ref('agent_id', 'agents', true),
    'PRIMARY KEY(team_id,agent_id)',
  ]),
  table('conversations', [
    id,
    'number BIGINT NOT NULL AUTO_INCREMENT UNIQUE',
    ref('user_id', 'users', true),
    "status VARCHAR(30) NOT NULL DEFAULT 'BOT' CHECK(status IN ('BOT','WAITING_FOR_AGENT','AGENT_IN_CHARGE','CLOSED'))",
    "subject TEXT NOT NULL DEFAULT ('บทสนทนาใหม่')",
    "category VARCHAR(255) NOT NULL DEFAULT 'ทั่วไป'",
    "priority VARCHAR(10) NOT NULL DEFAULT 'NORMAL' CHECK(priority IN ('NORMAL','HIGH'))",
    ref('assigned_agent_id', 'agents'),
    json('tags', '[]'),
    created,
    updated,
    time('handover_at'),
    time('claimed_at'),
    time('closed_at'),
    'resolution VARCHAR(50)',
    'close_note LONGTEXT',
    time('last_reminded_at'),
    'supervisor_alert_status VARCHAR(30)',
    time('supervisor_notified_at'),
    ref('team_id', 'teams'),
    'routing_version INT NOT NULL DEFAULT 0',
    'analysis_revision BIGINT NOT NULL DEFAULT 0',
    "CHECK((status='CLOSED')=(closed_at IS NOT NULL))",
    "open_user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin GENERATED ALWAYS AS (CASE WHEN status<>'CLOSED' THEN RTRIM(user_id) ELSE NULL END) STORED UNIQUE",
    'INDEX conversation_queue(status,updated_at)',
    'INDEX ticket_queue(team_id,status,updated_at)',
  ]),
  table('messages', [
    id,
    'sequence BIGINT NOT NULL AUTO_INCREMENT UNIQUE',
    ref('conversation_id', 'conversations', true),
    "sender_type VARCHAR(20) NOT NULL CHECK(sender_type IN ('USER','BOT','AGENT','SYSTEM'))",
    ref('agent_id', 'agents'),
    "kind VARCHAR(50) NOT NULL DEFAULT 'text'",
    'encrypted_text LONGTEXT',
    'encrypted_payload LONGTEXT',
    "redacted_text LONGTEXT NOT NULL DEFAULT ('')",
    "delivery_status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED' CHECK(delivery_status IN ('RECEIVED','QUEUED','ACCEPTED','FAILED','UNKNOWN','SIMULATED','CANCELLED'))",
    'internal BOOLEAN NOT NULL DEFAULT false',
    'line_message_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin UNIQUE',
    'client_request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin UNIQUE',
    'reply_token TEXT',
    time('reply_received_at'),
    'reply_reserved BOOLEAN NOT NULL DEFAULT false',
    json('metadata', '{}'),
    'attachment_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin',
    created,
    time('withdrawn_at'),
    'INDEX message_timeline(conversation_id,created_at,sequence)',
  ]),
  table('attachments', [
    id,
    ref('message_id', 'messages', true),
    'filename VARCHAR(255) NOT NULL',
    'mime_type VARCHAR(191) NOT NULL',
    'byte_size INT NOT NULL',
    'storage_path TEXT NOT NULL',
    created,
  ]),
  table('webhook_events', [
    'id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    'encrypted_payload LONGTEXT',
    "status VARCHAR(20) NOT NULL DEFAULT 'PENDING'",
    time('received_at', true),
    time('processed_at'),
  ]),
  table('withdrawn_line_messages', [
    'line_message_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    'line_user_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL',
    created,
  ]),
  table('jobs', [
    id,
    'kind VARCHAR(60) NOT NULL',
    'payload JSON NOT NULL',
    'dedupe_key VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin UNIQUE',
    "status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','RUNNING','DONE','FAILED'))",
    'attempts INT NOT NULL DEFAULT 0',
    time('run_at', true),
    time('locked_until'),
    'lease_token CHAR(36) CHARACTER SET ascii COLLATE ascii_bin',
    'last_error TEXT',
    created,
    time('completed_at'),
    'INDEX job_queue(status,run_at)',
  ]),
  table('knowledge_documents', [
    id,
    'filename VARCHAR(255) NOT NULL',
    'mime_type VARCHAR(191) NOT NULL',
    'byte_size INT NOT NULL',
    'sha256 VARCHAR(64) NOT NULL',
    'title VARCHAR(255) NOT NULL',
    'category VARCHAR(255) NOT NULL',
    ref('created_by', 'agents', true),
    created,
    "status VARCHAR(20) NOT NULL DEFAULT 'QUEUED' CHECK(status IN ('QUEUED','READY','FAILED','ARCHIVED'))",
    'pages INT',
    'empty_pages INT NOT NULL DEFAULT 0',
    'error TEXT',
  ]),
  table('knowledge', [
    id,
    'title VARCHAR(255) NOT NULL',
    'content LONGTEXT NOT NULL',
    'category VARCHAR(255) NOT NULL',
    json('keywords', '[]'),
    "status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','PUBLISHED','ARCHIVED'))",
    'version INT NOT NULL DEFAULT 1',
    'published_content LONGTEXT',
    'published_title VARCHAR(255)',
    json('published_keywords', '[]'),
    json('embedding'),
    'embedding_model VARCHAR(191)',
    ref('created_by', 'agents', true),
    ref('updated_by', 'agents', true),
    ref('approved_by', 'agents'),
    updated,
    time('published_at'),
    ref('document_id', 'knowledge_documents'),
    'source_page INT',
    'source_index INT',
    ref('source_message_id', 'messages'),
    'UNIQUE(document_id,source_index)',
  ]),
  table('knowledge_versions', [
    id,
    ref('knowledge_id', 'knowledge', true),
    'version INT NOT NULL',
    'title VARCHAR(255) NOT NULL',
    'content LONGTEXT NOT NULL',
    'keywords JSON NOT NULL',
    ref('approved_by', 'agents', true),
    time('published_at', true),
    'UNIQUE(knowledge_id,version)',
  ]),
  table('training_examples', [
    id,
    ref('conversation_id', 'conversations', true),
    'source_message_ids JSON NOT NULL',
    'question LONGTEXT NOT NULL',
    'answer LONGTEXT NOT NULL',
    json('context', '[]'),
    'category VARCHAR(255) NOT NULL',
    "notes TEXT NOT NULL DEFAULT ('')",
    "status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','APPROVED','REJECTED','REVOKED'))",
    ref('created_by', 'agents', true),
    ref('reviewed_by', 'agents'),
    time('reviewed_at'),
    created,
    updated,
  ]),
  table('datasets', [
    id,
    'version BIGINT NOT NULL AUTO_INCREMENT UNIQUE',
    'name VARCHAR(255) NOT NULL',
    ref('created_by', 'agents', true),
    created,
  ]),
  table('dataset_items', [
    ref('dataset_id', 'datasets', true, true),
    ref('example_id', 'training_examples', true),
    "split VARCHAR(20) NOT NULL CHECK(split IN ('train','validation','test'))",
    json('snapshot'),
    time('revoked_at'),
    'PRIMARY KEY(dataset_id,example_id)',
  ]),
  table('broadcasts', [
    id,
    'title VARCHAR(255) NOT NULL',
    'content LONGTEXT NOT NULL',
    "segment VARCHAR(20) NOT NULL CHECK(segment IN ('all','members','guests'))",
    "status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','SCHEDULED','SENDING','COMPLETED','FAILED','CANCELLED'))",
    time('scheduled_at'),
    ref('created_by', 'agents', true),
    created,
    json('filters', '{}'),
  ]),
  table('broadcast_batches', [
    id,
    ref('broadcast_id', 'broadcasts', true),
    'recipient_ids JSON NOT NULL',
    'retry_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL',
    "status VARCHAR(20) NOT NULL DEFAULT 'PENDING'",
    time('accepted_at'),
  ]),
  table('audit_logs', [
    'id BIGINT PRIMARY KEY AUTO_INCREMENT',
    ref('agent_id', 'agents'),
    'action VARCHAR(100) NOT NULL',
    'entity_type VARCHAR(60) NOT NULL',
    'entity_id VARCHAR(191)',
    json('details', '{}'),
    created,
  ]),
  table('settings', [
    '`key` VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    '`value` JSON NOT NULL',
    updated,
  ]),
  table('sso_transactions', [
    'state_hash VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    'browser_hash VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL',
    'line_user_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL',
    'verifier TEXT NOT NULL',
    'expires_at DATETIME(3) NOT NULL',
    created,
  ]),
  table('case_transfers', [
    id,
    ref('conversation_id', 'conversations', true),
    ref('from_team_id', 'teams'),
    ref('to_team_id', 'teams', true),
    ref('from_agent_id', 'agents'),
    ref('to_agent_id', 'agents'),
    ref('created_by', 'agents', true),
    'from_team_name VARCHAR(200)',
    'to_team_name VARCHAR(200) NOT NULL',
    'from_agent_name VARCHAR(255)',
    'to_agent_name VARCHAR(255)',
    'encrypted_reason LONGTEXT',
    'redacted_reason LONGTEXT NOT NULL',
    'request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE',
    'routing_version INT NOT NULL',
    ref('accepted_by', 'agents'),
    time('accepted_at'),
    created,
    'UNIQUE(conversation_id,routing_version)',
  ]),
  table('notifications', [
    id,
    ref('agent_id', 'agents', true),
    ref('conversation_id', 'conversations', true),
    ref('transfer_id', 'case_transfers', true),
    'title VARCHAR(500) NOT NULL',
    time('read_at'),
    created,
    'UNIQUE(agent_id,transfer_id)',
    'INDEX notification_inbox(agent_id,created_at)',
    "line_status VARCHAR(30) NOT NULL DEFAULT 'NOT_CONFIGURED' CHECK(line_status IN ('NOT_CONFIGURED','PENDING','ACCEPTED','SIMULATED','FAILED','CANCELLED'))",
    'line_payload LONGTEXT',
    time('line_sent_at'),
    'line_error TEXT',
  ]),
];

export const mysqlUuidTables = new Set([
  'agents',
  'users',
  'teams',
  'conversations',
  'messages',
  'attachments',
  'jobs',
  'knowledge',
  'knowledge_versions',
  'training_examples',
  'datasets',
  'broadcasts',
  'broadcast_batches',
  'case_transfers',
  'notifications',
  'knowledge_gaps',
]);
// Gaps reference knowledge and messages, so create them after both tables.
mysqlSchema.push(
  table('knowledge_gaps', [
    id,
    ref('conversation_id', 'conversations', true),
    ref('message_id', 'messages', true),
    'UNIQUE(message_id)',
    'question LONGTEXT NOT NULL',
    'reason VARCHAR(100) NOT NULL',
    "status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','DRAFTED','DISMISSED','REVOKED'))",
    ref('knowledge_id', 'knowledge'),
    created,
  ]),
  table('conversation_analyses', [
    ref('conversation_id', 'conversations', true),
    'PRIMARY KEY(conversation_id)',
    'revision BIGINT NOT NULL',
    "status VARCHAR(20) NOT NULL CHECK(status IN ('QUEUED','READY','FAILED'))",
    'model VARCHAR(191) NOT NULL',
    json('result'),
    json('source_message_ids', '[]'),
    json('coverage'),
    'error TEXT',
    time('analyzed_at'),
    time('requested_at', true),
  ]),
);

mysqlSchema.push(
  table('staff_identities', [
    'cusa_sub CHAR(36) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    'application_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL',
    ref('agent_id', 'agents', true),
    'UNIQUE(agent_id)',
    created,
  ]),
  table('staff_sso_sessions', [
    'token_hash VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    'FOREIGN KEY (token_hash) REFERENCES auth_sessions(token_hash) ON DELETE CASCADE',
    'cusa_sub CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL',
    'FOREIGN KEY (cusa_sub) REFERENCES staff_identities(cusa_sub)',
    'encrypted_token TEXT NOT NULL',
  ]),
  table('staff_sso_transactions', [
    'state_hash VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    'browser_hash VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL',
    'verifier TEXT NOT NULL',
    'expires_at DATETIME(3) NOT NULL',
    created,
  ]),
);

// Additive migration: existing staff sessions remain valid until their original expiry.
mysqlSchema.push(
  table('staff_sso_refresh', [
    'token_hash VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    'FOREIGN KEY (token_hash) REFERENCES auth_sessions(token_hash) ON DELETE CASCADE',
    'encrypted_refresh_token TEXT NOT NULL',
    'access_expires_at DATETIME(3) NOT NULL',
    'refresh_expires_at DATETIME(3) NOT NULL',
    'api_key_hash VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL',
    'scopes TEXT NOT NULL',
    'rotation_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin',
    'rotation_started_at DATETIME(3)',
  ]),
);

mysqlSchema.push(
  table('line_chats', [
    'id CHAR(33) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    "type VARCHAR(10) NOT NULL CHECK(type IN ('group','room'))",
    'active BOOLEAN NOT NULL',
    'last_event_at DATETIME(3) NOT NULL',
    updated,
  ]),
  table('line_claim_events', [
    'id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY',
    ref('conversation_id', 'conversations'),
    'encrypted_response LONGTEXT NOT NULL',
    'reply_attempted BOOLEAN NOT NULL DEFAULT false',
    created,
  ]),
);
