export type AgentRole = 'ADMIN' | 'AGENT' | 'REVIEWER';
export type Agent = { id: string; name: string; email: string; role: AgentRole };
export type StaffAccount = {
  agent: Agent;
  demo: boolean;
  line: {
    userId: string | null;
    source: 'SSO' | 'OA_LINK' | null;
    verified: boolean;
    enabled: boolean;
  };
  lineManagedBySso: boolean;
  canLinkLine: boolean;
};
export type CaseState = 'BOT' | 'WAITING_FOR_AGENT' | 'AGENT_IN_CHARGE' | 'CLOSED';
export type DeliveryState =
  'RECEIVED' | 'QUEUED' | 'ACCEPTED' | 'FAILED' | 'UNKNOWN' | 'SIMULATED' | 'CANCELLED';
export type Conversation = {
  id: string;
  number: number;
  user_id: string;
  status: CaseState;
  subject: string;
  category: string;
  priority: 'NORMAL' | 'HIGH';
  assigned_agent_id: string | null;
  assigned_agent_name: string | null;
  team_id: string | null;
  team_name: string | null;
  routing_version: number;
  created_at: string;
  updated_at: string;
  handover_at: string | null;
  supervisor_alert_status: string | null;
  supervisor_notified_at: string | null;
  claimed_at: string | null;
  closed_at: string | null;
  resolution: string | null;
  close_note: string | null;
  tags: string[];
  name: string;
  line_display_name: string | null;
  department: string | null;
  cusa_sub: string | null;
  avatar_color: string;
  last_message: string | null;
  message_count: number;
  training_status: string | null;
};
export type Message = {
  id: string;
  conversation_id: string;
  sender_type: 'USER' | 'BOT' | 'AGENT' | 'SYSTEM';
  agent_id: string | null;
  agent_name: string | null;
  kind: string;
  text: string;
  redacted_text: string;
  delivery_status: DeliveryState;
  internal: boolean;
  created_at: string;
  withdrawn_at: string | null;
  metadata: Record<string, unknown>;
  attachment_id: string | null;
};
export type Team = {
  id: string;
  name: string;
  description: string;
  active: boolean;
  members: Pick<Agent, 'id' | 'name' | 'role'>[];
};
export type CaseTransfer = {
  id: string;
  from_team_name: string | null;
  to_team_name: string;
  from_agent_name: string | null;
  to_agent_name: string | null;
  created_by_name: string;
  created_at: string;
  reason: string;
  accepted_by_name: string | null;
  accepted_by: string | null;
  accepted_at: string | null;
};
export type TrainingExample = {
  id: string;
  conversation_id: string;
  status: 'DRAFT' | 'APPROVED' | 'REJECTED' | 'REVOKED';
  question: string;
  answer: string;
  category: string;
  notes: string;
  context: { role: 'user' | 'assistant'; content: string }[];
  created_by: string;
  created_by_name: string;
  reviewed_by: string | null;
  reviewed_by_name: string | null;
  created_at: string;
  updated_at: string;
  case_number: number;
  source_message_ids: string[];
};
export type Knowledge = {
  id: string;
  title: string;
  content: string;
  category: string;
  keywords: string[];
  status: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';
  version: number;
  created_by: string;
  updated_at: string;
  published_content: string | null;
  document_id: string | null;
  source_page: number | null;
  source_message_id: string | null;
};
export type DashboardStats = {
  total: number;
  waiting: number;
  active: number;
  closed: number;
  bot: number;
  approved_examples: number;
  draft_examples: number;
  published_knowledge: number;
  daily: { day: string; count: number; human: number }[];
  categories: { category: string; count: number }[];
  recent: Conversation[];
  operations: {
    claimed: number;
    within_target: number;
    average_seconds: number | null;
    p90_seconds: number | null;
    overdue: number;
    failed_alerts: number;
    target_minutes: number;
    supervisor_configured: boolean;
    hourly: { hour: number; count: number }[];
  };
};
